[modify] 購入確認画面でポイント使用をクリックしたときに配送日時が保存されるように修正。
EC-CUBE/point-plugin pull request #148
Opened 2017-07-25 17:47 UTC by tomgoodsun

購入確認画面でポイント使用ボタンをクリックすると使用ポイント入力フォームに遷移しますが、購入確認画面に戻ってきたときに設定されていた配送日時が未選択状態になってしまうのを修正しました。
お届け先変更処理を参考にしました。

2017-10-26 10:55 UTC, ryo-endo requested changes
PRありがとうございます。
レビュー遅くなり申し訳ありません。
コードで気になった点がいくつかございましたので修正をお願いできますでしょうか？

2017-10-26 10:55 UTC, ryo-endo commented on Controller/FrontPointController.php
> +        if ('POST' !== $request->getMethod()) {
L58`$form->isSubmitted()`でチェックしているので、こちらの条件は不要となります。

2017-10-26 10:55 UTC, ryo-endo commented on Controller/FrontPointController.php
> +        $event = new EventArgs(
`$event` はそれ以降の処理で利用していないので、不要だと思います。

2017-10-26 10:55 UTC, ryo-endo commented on Controller/FrontPointController.php
> +            $app['orm.em']->flush();
プラグイン側で引数無しのflush()を行うと、
意図しない影響を与える可能性がありますので、引数でEntityを指定するようにお願いします。
おそらく`$app['orm.em']->flush($Order);`でよいかと。

2018-01-11 09:28 UTC, tomgoodsun commented on Controller/FrontPointController.php
> +            $app['orm.em']->flush();
`$app['orm.em']->flush($Order);`
これだと配送時間が保存されないようです。
以下のような感じで修正しました。
```
foreach ($Order->getShippings() as $Shipping) {
    // 配送情報を更新
    $app['orm.em']->flush($Shipping);
}
```

2018-01-11 09:32 UTC, tomgoodsun commented
こちらもだいぶ放置しててすみません。
不要箇所は削除しました。

`$app['orm.em']->flush($Order);`
これだと配送時間が保存されないようです。
以下のような感じで修正しました。
```
foreach ($Order->getShippings() as $Shipping) {
    // 配送情報を更新
    $app['orm.em']->flush($Shipping);
}
```
この修正で妥当でしょうか。

2019-07-29 01:32 UTC, closed without merging